workers_dev = true
name = "iqbal-live"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }
pages_build_output_dir = './build'

[observability.logs]
enabled = true
